/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.consumersurveys.model;

/**
 * Specifications for the target audience of a surveys run through the API.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Consumer Surveys API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SurveyAudience extends com.google.api.client.json.GenericJson {

  /**
   * Optional list of age buckets to target. Supported age buckets are: ['18-24', '25-34', '35-44',
   * '45-54', '55-64', '65+']
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> ages;

  /**
   * Required country code that surveys should be targeted to. Accepts standard ISO 3166-1 2
   * character language codes, e.g. 'US'.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String country;

  /**
   * Optional gender to target.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gender;

  /**
   * Language code that surveys should be targeted to, e.g. 'en-US'. Surveys may target bilingual
   * users by specifying a list of language codes (e.g. 'de' and 'en-US'). In that case, all
   * languages will be used for targeting users but the survey content (which is displayed) must
   * match the first language listed. Accepts standard BCP47 language codes. See:
   * https://tools.ietf.org/html/bcp47
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> languages;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String populationSource;

  /**
   * Optional list of age buckets to target. Supported age buckets are: ['18-24', '25-34', '35-44',
   * '45-54', '55-64', '65+']
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getAges() {
    return ages;
  }

  /**
   * Optional list of age buckets to target. Supported age buckets are: ['18-24', '25-34', '35-44',
   * '45-54', '55-64', '65+']
   * @param ages ages or {@code null} for none
   */
  public SurveyAudience setAges(java.util.List<java.lang.String> ages) {
    this.ages = ages;
    return this;
  }

  /**
   * Required country code that surveys should be targeted to. Accepts standard ISO 3166-1 2
   * character language codes, e.g. 'US'.
   * @return value or {@code null} for none
   */
  public java.lang.String getCountry() {
    return country;
  }

  /**
   * Required country code that surveys should be targeted to. Accepts standard ISO 3166-1 2
   * character language codes, e.g. 'US'.
   * @param country country or {@code null} for none
   */
  public SurveyAudience setCountry(java.lang.String country) {
    this.country = country;
    return this;
  }

  /**
   * Optional gender to target.
   * @return value or {@code null} for none
   */
  public java.lang.String getGender() {
    return gender;
  }

  /**
   * Optional gender to target.
   * @param gender gender or {@code null} for none
   */
  public SurveyAudience setGender(java.lang.String gender) {
    this.gender = gender;
    return this;
  }

  /**
   * Language code that surveys should be targeted to, e.g. 'en-US'. Surveys may target bilingual
   * users by specifying a list of language codes (e.g. 'de' and 'en-US'). In that case, all
   * languages will be used for targeting users but the survey content (which is displayed) must
   * match the first language listed. Accepts standard BCP47 language codes. See:
   * https://tools.ietf.org/html/bcp47
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getLanguages() {
    return languages;
  }

  /**
   * Language code that surveys should be targeted to, e.g. 'en-US'. Surveys may target bilingual
   * users by specifying a list of language codes (e.g. 'de' and 'en-US'). In that case, all
   * languages will be used for targeting users but the survey content (which is displayed) must
   * match the first language listed. Accepts standard BCP47 language codes. See:
   * https://tools.ietf.org/html/bcp47
   * @param languages languages or {@code null} for none
   */
  public SurveyAudience setLanguages(java.util.List<java.lang.String> languages) {
    this.languages = languages;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPopulationSource() {
    return populationSource;
  }

  /**
   * @param populationSource populationSource or {@code null} for none
   */
  public SurveyAudience setPopulationSource(java.lang.String populationSource) {
    this.populationSource = populationSource;
    return this;
  }

  @Override
  public SurveyAudience set(String fieldName, Object value) {
    return (SurveyAudience) super.set(fieldName, value);
  }

  @Override
  public SurveyAudience clone() {
    return (SurveyAudience) super.clone();
  }

}
