/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-07-16 20:05:20 UTC)
 * on 2015-07-27 at 21:27:10 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.consumersurveys.model;

/**
 * Model definition for SurveysListResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Consumer Surveys API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SurveysListResponse extends com.google.api.client.json.GenericJson {

  /**
   * Survey object containing the specifications.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Survey> resources;

  /**
   * Survey object containing the specifications.
   * @return value or {@code null} for none
   */
  public java.util.List<Survey> getResources() {
    return resources;
  }

  /**
   * Survey object containing the specifications.
   * @param resources resources or {@code null} for none
   */
  public SurveysListResponse setResources(java.util.List<Survey> resources) {
    this.resources = resources;
    return this;
  }

  @Override
  public SurveysListResponse set(String fieldName, Object value) {
    return (SurveysListResponse) super.set(fieldName, value);
  }

  @Override
  public SurveysListResponse clone() {
    return (SurveysListResponse) super.clone();
  }

}
