/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-07-16 20:05:20 UTC)
 * on 2015-07-27 at 21:27:10 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.consumersurveys.model;

/**
 * Message defining the cost to run a given survey through API.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Consumer Surveys API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SurveyCost extends com.google.api.client.json.GenericJson {

  /**
   * Currency code that the cost is given in.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String currencyCode;

  /**
   * Cost of survey in nano units of the given currency.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long nanos;

  /**
   * Currency code that the cost is given in.
   * @return value or {@code null} for none
   */
  public java.lang.String getCurrencyCode() {
    return currencyCode;
  }

  /**
   * Currency code that the cost is given in.
   * @param currencyCode currencyCode or {@code null} for none
   */
  public SurveyCost setCurrencyCode(java.lang.String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

  /**
   * Cost of survey in nano units of the given currency.
   * @return value or {@code null} for none
   */
  public java.lang.Long getNanos() {
    return nanos;
  }

  /**
   * Cost of survey in nano units of the given currency.
   * @param nanos nanos or {@code null} for none
   */
  public SurveyCost setNanos(java.lang.Long nanos) {
    this.nanos = nanos;
    return this;
  }

  @Override
  public SurveyCost set(String fieldName, Object value) {
    return (SurveyCost) super.set(fieldName, value);
  }

  @Override
  public SurveyCost clone() {
    return (SurveyCost) super.clone();
  }

}
