/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-07-16 20:05:20 UTC)
 * on 2015-07-27 at 21:27:10 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.consumersurveys.model;

/**
 * Response message for API requests to get survey results.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Consumer Surveys API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SurveyResults extends com.google.api.client.json.GenericJson {

  /**
   * Human readable string describing the status of the request
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * External survey id as viewable by survey owners in the editor view.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String surveyUrlId;

  /**
   * Human readable string describing the status of the request
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * Human readable string describing the status of the request
   * @param status status or {@code null} for none
   */
  public SurveyResults setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  /**
   * External survey id as viewable by survey owners in the editor view.
   * @return value or {@code null} for none
   */
  public java.lang.String getSurveyUrlId() {
    return surveyUrlId;
  }

  /**
   * External survey id as viewable by survey owners in the editor view.
   * @param surveyUrlId surveyUrlId or {@code null} for none
   */
  public SurveyResults setSurveyUrlId(java.lang.String surveyUrlId) {
    this.surveyUrlId = surveyUrlId;
    return this;
  }

  @Override
  public SurveyResults set(String fieldName, Object value) {
    return (SurveyResults) super.set(fieldName, value);
  }

  @Override
  public SurveyResults clone() {
    return (SurveyResults) super.clone();
  }

}
